version: '2'
services:
    quickandclean-app:
        image: quickandclean
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://quickandclean-mysql:3306/quickandclean?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=quickandclean-elasticsearch:9300
        ports:
            - 8080:8080
    quickandclean-mysql:
        extends:
            file: mysql.yml
            service: quickandclean-mysql
    quickandclean-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: quickandclean-elasticsearch
